// orders constraints
const MAX_BOOKS_IN_ORDER = 3;
const MAX_ACTIVE_ORDERS_SIMULTANEOUSLY = 1;

// info badges time to show
const HIDE_AFTER_SHORT_MSEC = 2300;
const HIDE_AFTER_DEFAULT_MSEC = 5000;
const HIDE_AFTER_LONG_MSEC = 10000;

// pagination
const AUTHORS_PER_PAGE = 3;
const BOOKS_PER_PAGE = 6;

// caching
const CACHED_BOOKS_TTL_SEC = 86400;
const CACHED_AUTHORS_TTL_SEC = 86400;

export {
  MAX_BOOKS_IN_ORDER,
  MAX_ACTIVE_ORDERS_SIMULTANEOUSLY,
  HIDE_AFTER_SHORT_MSEC,
  HIDE_AFTER_DEFAULT_MSEC,
  HIDE_AFTER_LONG_MSEC,
  AUTHORS_PER_PAGE,
  BOOKS_PER_PAGE,
  CACHED_BOOKS_TTL_SEC,
  CACHED_AUTHORS_TTL_SEC,
};
