const MAX_BOOKS_IN_ORDER = 3;
const MAX_ACTIVE_ORDERS_SIMULTANEOUSLY = 1;
const HIDE_AFTER_DEFAULT_MILLISECONDS = 5000;

export {
  MAX_BOOKS_IN_ORDER,
  MAX_ACTIVE_ORDERS_SIMULTANEOUSLY,
  HIDE_AFTER_DEFAULT_MILLISECONDS,
};
