const MAX_BOOKS_IN_ORDER = 3;
const MAX_ACTIVE_ORDERS_SIMULTANEOUSLY = 1;
const HIDE_AFTER_SHORT_MILLISECONDS = 2300;
const HIDE_AFTER_DEFAULT_MILLISECONDS = 5000;
const HIDE_AFTER_LONG_MILLISECONDS = 10000;

export {
  MAX_BOOKS_IN_ORDER,
  MAX_ACTIVE_ORDERS_SIMULTANEOUSLY,
  HIDE_AFTER_SHORT_MILLISECONDS,
  HIDE_AFTER_DEFAULT_MILLISECONDS,
  HIDE_AFTER_LONG_MILLISECONDS,
};
